### PR TITLE
GitHub host

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by tim-moody** [comment]
we need to determine if regions.json is still used

**Comment by jvonau** [comment]
and https://github.com/iiab/iiab-admin-console/pull/483#issuecomment-1108948986

**Comment by tim-moody** [comment]
For adm cons I see:
adm_lib get_map_catalog() reads /maplist/assets/regions.json
and this is called only by iiab-update-map3.py
that has two functions:
1) update the home page menu with an appropriate menu def, which I think we no longer want
2) update the osm home page to redirect from the test page to an installed map, which now is always viewer

**Comment by jvonau** [comment]
Should be fine once the regions.json file is corrected, the goal here is to have http://download.iiab.io/content/OSM/vector-tiles/maplist/hidden/ and http://timmoody.com/iiab-files/maps/ replaced with github as the authoritative source for these 3 files.

**Comment by jvonau** [comment]
> For adm cons I see: adm_lib get_map_catalog() reads /maplist/assets/regions.json and this is called only by iiab-update-map3.py that has two functions:
> 
>     1. update the home page menu with an appropriate menu def, which I think we no longer want

This works nicely as per chat observations, think that is still wanted
>     2. update the osm home page to redirect from the test page to an installed map, which now is always viewer

That is not quite true as per observations noted in chat 'installer' is the default until more maps are installed then 'viewer' is used.

**Comment by holta** [comment]
> Lets keep the new file in a new directory

This is a good idea.

Let's also think carefully about the naming of the directory to avoid all confusion in future if possible &mdash; as George refers to this IIAB Maps effort over the last 4 months as the "2020" version &mdash; in connection with the new OSM data files from late 2020 that we're working with here.

**Pull request merged**
