### PR TITLE
7.2 devel - Install Script Added

### PR DESCRIPTION
**Pull request by siriuswapnil**
Created an install script. Also a script for copying all the files to the required location.

### CODE REVIEW

**Comment by tim-moody** [comment]
couple of comments:

1. is there are reason to modify index.html in webpack/build? Isn't that where the built files will go? The source is in https://github.com/iiab/maps/tree/7.2-devel/osm-source/viewer?

1. Do we need assets in webpack? Doesn't it belong in viewer?

1. I thought the install script would npm the packages needed.

1. Now I'm confused. Is the source to be built (main.js) in webpack or osm-source/viewer? I think we are only building javascript.

**Comment by siriuswapnil** [comment]
My intention behind those scripts was to get the right things from the right places and install in one go.

**Comment by tim-moody** [comment]
@georgejhunt can you weigh in on our devel, build, and prod environments?

**Comment by siriuswapnil** [comment]
Changes: 
1) Files under node_modules added to .gitignore
2) Copy statements in installscript.sh removed.
3) up.sh modified to not to copy build files to webpack/
4) Webpack directory removed.

**Pull request merged**
