### PR TITLE
RFC Osm pylint

### PR DESCRIPTION
**Pull request by jvonau**
Should be running pylint against the python code
passes pylint with 2 warning left

`pylint osm-source/pages/viewer/scripts/iiab-maps-finish.py`
>************* Module iiab-maps-finish
osm-source/pages/viewer/scripts/iiab-maps-finish.py:1:0: C0103: Module name "iiab-maps-finish" doesn't conform to snake_case naming style (invalid-name)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:56:4: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)

------------------------------------------------------------------
>Your code has been rated at 9.72/10 (previous run: 9.03/10, +0.69)

I get a funny feeling iiab-make-init.py isn't being used going forward, didn't test that one, please confirm.
Running pylint againt master, sniped a bunch of stuff, run pylint for yourself to see
`pylint osm-source/pages/viewer/scripts/iiab-maps-finish.py`
>------------------------------------------------------------------
Your code has been rated at 2.75/10 (previous run: 9.72/10, -6.97)

### CODE REVIEW

**Comment by holta** [comment]
Very positive — making code/infra approachable allows for a healthy & inviting & growing community.

This one below is not so positive (i.e. a negative score) but one step at a time 😄

```
pylint /usr/bin/iiab-extend-sat.py

"Your code has been rated at -6.44/10"
```

Output:
http://sprunge.us/wcWM0U?en

Regarding:
https://github.com/iiab/maps/blob/master/osm-source/pages/viewer/scripts/iiab-extend-sat.py

**Comment by tim-moody** [comment]
I'm not a big fan of pylint as I find it too pedantic. I do care a lot about variable names and intelligibility in general.

https://www.earthdatascience.org/courses/intro-to-earth-data-science/write-efficient-python-code/intro-to-clean-code/expressive-variable-names-make-code-easier-to-read/#:~:text=Use%20meaningful%20names%3A%20A%20meaningful,are%20NOT%20VALID%20in%20Python. says some useful things.

A couple of comments:

- map is not a keyword, though it is a builtin function, so using it as a variable name is not illegal and there would be no confusion in this context
- I follow the convention to use nouns for variables and verbs (or verb clauses) for functions, so I would never name a variable get_catalog
- MAP_CATALOG = {} is not a constant; it is a global variable, so I would not make it upper case
- my own convention is to use plural for aggregates of items and singular for an individual item, so tilesets[tileset]
- there's nothing illegal about if ...: continue. I don't do this much, but at times it can actually improve readability

I think the most important thing is readability and intelligibility, not following the at times idiosyncratic conventions of the author of pylint.

**Comment by jvonau** [comment]
jvonau@kickass:/mnt/scratch/git/maps$ `pep8 osm-source/pages/viewer/scripts/iiab-maps-finish.py` vs master
```
osm-source/pages/viewer/scripts/iiab-maps-finish.py:1:19: W291 trailing whitespace
osm-source/pages/viewer/scripts/iiab-maps-finish.py:8:11: E401 multiple imports on one line
osm-source/pages/viewer/scripts/iiab-maps-finish.py:21:4: E111 indentation is not a multiple of four
osm-source/pages/viewer/scripts/iiab-maps-finish.py:22:4: E111 indentation is not a multiple of four
osm-source/pages/viewer/scripts/iiab-maps-finish.py:24:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:30:5: E265 block comment should start with '# '
osm-source/pages/viewer/scripts/iiab-maps-finish.py:33:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:38:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:44:26: E701 multiple statements on one line (colon)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:59:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:63:8: E111 indentation is not a multiple of four
osm-source/pages/viewer/scripts/iiab-maps-finish.py:63:45: E701 multiple statements on one line (colon)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:64:8: E111 indentation is not a multiple of four
osm-source/pages/viewer/scripts/iiab-maps-finish.py:64:55: E701 multiple statements on one line (colon)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:65:8: E111 indentation is not a multiple of four
osm-source/pages/viewer/scripts/iiab-maps-finish.py:68:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:69:80: E501 line too long (84 > 79 characters)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:70:80: E501 line too long (85 > 79 characters)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:73:1: E302 expected 2 blank lines, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:78:5: E265 block comment should start with '# '
osm-source/pages/viewer/scripts/iiab-maps-finish.py:79:7: E114 indentation is not a multiple of four (comment)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:79:7: E116 unexpected indentation (comment)
osm-source/pages/viewer/scripts/iiab-maps-finish.py:79:7: E265 block comment should start with '# '
osm-source/pages/viewer/scripts/iiab-maps-finish.py:80:8: E221 multiple spaces before operator
osm-source/pages/viewer/scripts/iiab-maps-finish.py:80:37: E231 missing whitespace after ','
osm-source/pages/viewer/scripts/iiab-maps-finish.py:81:7: E271 multiple spaces after keyword
osm-source/pages/viewer/scripts/iiab-maps-finish.py:82:63: E228 missing whitespace around modulo operator
osm-source/pages/viewer/scripts/iiab-maps-finish.py:89:31: W291 trailing whitespace
osm-source/pages/viewer/scripts/iiab-maps-finish.py:90:43: W291 trailing whitespace
osm-source/pages/viewer/scripts/iiab-maps-finish.py:91:43: W291 trailing whitespace
osm-source/pages/viewer/scripts/iiab-maps-finish.py:93:22: E231 missing whitespace after ','
osm-source/pages/viewer/scripts/iiab-maps-finish.py:94:38: E231 missing whitespace after ','
osm-source/pages/viewer/scripts/iiab-maps-finish.py:101:1: E305 expected 2 blank lines after class or function definition, found 1
osm-source/pages/viewer/scripts/iiab-maps-finish.py:102:4: E111 indentation is not a multiple of four
```

**Comment by georgejhunt** [comment]
iiab-make-init.py has a function when admin-console is not installed, and when testing the map system without a dependency on admin-console.  But admin-console shadows it.

I think it is dangerous to make too many changes to code without thorough testing. I will not volunteer. But there seems to be a willingness for that among the rest of you. 

The main function of iiab-extend-sat.py is to add more satellite tiles to a region.   I consider it very fragile. I've avoided more than the minimal changes necessary to keep its function. It's really a general purpose program which has only one purpose.

**Comment by holta** [comment]
> iiab-make-init.py has a function when admin-console is not installed, and when testing the map system without a dependency on admin-console. But admin-console shadows it.

Thanks for mentioning that (66-line [/usr/bin/iiab-make-init.py](https://github.com/iiab/maps/blob/master/osm-source/pages/viewer/scripts/iiab-make-init.py)).

> I think it is dangerous to make too many changes to code without thorough testing. I will not volunteer. But there seems to be a willingness for that among the rest of you.

So long as we test the most critical code paths, everyone will benefit.

By building up an understanding step by step, while investing in the future.

> The main function of iiab-extend-sat.py is to add more satellite tiles to a region. I consider it very fragile. I've avoided more than the minimal changes necessary to keep its function. It's really a general purpose program which has only one purpose.

Thanks for explaining.  Good to know that 844-line [/usr/bin/iiab-extend-sat.py](https://github.com/iiab/maps/blob/master/osm-source/pages/viewer/scripts/iiab-extend-sat.py) is based on 134-line https://github.com/TimSC/pyMbTiles/blob/master/MBTiles.py

(It works quite well to date, in my experience!)

**Comment by jvonau** [comment]
> I'm not a big fan of pylint as I find it too pedantic. I do care a lot about variable names and intelligibility in general.

Using pylint did confirm my suspicions that the iiab.iiab_lib module was not being imported properly https://github.com/iiab/maps/pull/61#issuecomment-1115096361, along with pointing out other unused imports.

> map is not a keyword, though it is a builtin function, so using it as a variable name is not illegal and there would be no confusion in this context

May not be 'illegal', but there would be some confusion when somebody else looks at the code as I did, don't think redefining a buildin function is a good practice.

>there's nothing illegal about if ...: continue. I don't do this much, but at times it can actually improve readability

Again that is not 'illegal', just not a best practice and actually decrease readabilty as that practice departs from the expected norms.

>I think the most important thing is readability and intelligibility, not following the at times idiosyncratic conventions of the author of pylint.

I would expect any code to adhere to the accepted norms of the language the code was written in.

>iiab-make-init.py has a function when admin-console is not installed, and when testing the map system without a dependency on admin-console. But admin-console shadows it.

I don't see where iiab-make-init.py is used any longer I can't find any mention of it with ` grep -r iiab-make-init.py`. It appears that iiab-maps-finish.py is has been called by iiab-install-map-region for a long time now and handles both the init.json file and vector-map-idx.json.

>The main function of iiab-extend-sat.py is to add more satellite tiles to a region. I consider it very fragile. I've avoided more than the minimal changes necessary to keep its function. It's really a general purpose program which has only one purpose.

I understand the fragility of the code that is why one should keep to the accepted standards of the language the code is written in, to be able to use the available tools to double check the code as written.

**Comment by jvonau** [comment]
> MAP_CATALOG = {} is not a constant; it is a global variable, so I would not make it upper case

Removed.
> I follow the convention to use nouns for variables and verbs (or verb clauses) for functions, so I would never name a variable get_catalog

I went with source_catalog, is that better?

**Comment by holta** [comment]
FYI this repo http://github.com/iiab/maps was just pruned from 123MB to 26MB, removing all blobs 10MB-or-larger, using: https://rtyley.github.io/bfg-repo-cleaner/

PLEASE DO NOT POLLUTE THE REPO BY ADDING THE ~100MB of Git history / stale commits / blobs back in, e.g. with an older PR arising from an older fork/clone, Thanks !!

RECAP:

```
Deleted files...

        Filename            Git id
        ----------------------------------------------------------
        cities1000.sqlite | 2c3d950d (25.3 MB), b261403a (25.4 MB)
        detail.mbtiles    | 55cd011f (33.8 MB)
        ngrok             | fe1c05bc (25.2 MB)


root@box:/opt/iiab# more maps.git.bfg-report/2022-07-21/12-42-15/deleted-files.txt

2c3d950d93bdab4aab634a7d81b5dae468c3140f 26574848 cities1000.sqlite
b261403a3e96a5ca291f90f0f216f41ecd6e7513 26641408 cities1000.sqlite
55cd011f7aa01c1756bb63ea508ab2482e54ae8b 35438592 detail.mbtiles
fe1c05bcc8cd815e5d1d78b7fd0331362e78d37a 26441052 ngrok
```

Official instructions from BFG:

> "At this point, you're ready for everyone to ditch their old copies of the repo and do fresh clones of the nice, new pristine data. It's best to delete all old clones, as they'll have dirty history that you don't want to risk pushing back into your newly cleaned repo."

Related:

- PR #66

**Comment by georgejhunt** [comment]
I hope you have not made all the history in my experimental branches of the
map repo un-reachable. It sounds like you have changed the git index
without knowing if any of my branches reference it.

**Comment by holta** [comment]
> I hope you have not made all the history in my experimental branches of the map repo un-reachable.

No.

There's really no such thing as "unreachable" (git merges and rebases are both based on the idea of the DAG Common Ancestor).

Certainly if you submit PR's that drag back in almost 100MB of obsolete (deleted) blobs, that's much less elegant than rebasing.  Avoid it if you can.  So BFG pruning doesn't have to be painstakingly repeated.

We should all become better at rebasing and cherry-picking commits that truly matter.

Both are inherent parts of collaborating among contributors (practice makes perfect, naturally).

Another alternative is of course to copy an older file tree into a fresh fork/clone — anyway that's another option — similar to squashing commits.

**Comment by holta** [comment]
> similar to squashing commits

As an example, this PR is a good candidate to have its commits squashed.

(While we haven't done it much to date, squashing commits is 100% normal as part of many dev communities.  And I can do it here if necessary.)

> Another alternative is of course to copy an older file tree into a fresh fork/clone — anyway that's another [even safer/cleaner] option [in this specific case].

For example, to keep the new repo clean from cruft, in this case if @georgejhunt and others believe this PR is now ready to merge, I can copy + paste the 4 files in this PR (takes less than 1 minute) and then attribute the work to @jvonau.

**Comment by holta** [comment]
> copy + paste the [~2 NOT 4] files in this PR (takes less than 1 minute)

Really this PR is about linting just 2 files:

- osm-source/pages/viewer/scripts/iiab-make-init.py
- osm-source/pages/viewer/scripts/iiab-maps-finish.py

Thanks to @jvonau and @tim-moody who helped here.

ASIDE: Currently this PR also drags in the older 25.4MB cities1000.sqlite (which is obviously to be avoided!)

**Comment by tim-moody** [comment]
map2 and map3 could both be maps. map2 serves no purpose after this renaming and I don't see the reason to reread map3 (also in the original) since there was an exit if map2 failed. again there is no built-in variable map and the assignment to one does not redefine a function of the same name.

**Comment by holta** [comment]
Just FYI triple quotes are not really comments in Python, but [docstrings (PEP 257)](https://peps.python.org/pep-0257/) that (when used as the first statement in a module, function, class, or method definition) set that object's `__doc__` attribute string literal.  Example:

```
>>> def bla():
...     """Print the answer"""
...     print 42
...
>>> bla.__doc__
'Print the answer'
>>> help(bla)
Help on function bla in module __main__:

bla()
    Print the answer
```

PS `"""` and `'''` both work.

**Comment by tim-moody** [comment]
it's true that the triple quotes not immediately after defs will probably not do anything and the others are of minimal utility given the size of this module.

**Comment by holta** [comment]
Personally I favor descriptive in-line "Gherkin story" comments (i.e. the narrative of the inventor).

Especially when these greatly increase code understandability-hence-maintainability &mdash; surfacing bugs earlier-rather-than-years-later.

(But I had not seen triple quotes before, so I looked it up!)

**Comment by jvonau** [comment]
No interest in correcting deficiencies - open source with a closed community

**Pull request closed without merging**
