### PR TITLE
Added support for multiple geojson files.

### PR DESCRIPTION
**Pull request by siriuswapnil**
New files included: 
- jsonserver.php  - a simple script to return the geojson file names in an array.
- relevant geojson files.

### CODE REVIEW

**Comment by tim-moody** [comment]
Hard for me to believe that this PR has been tested as I highly doubt it will work.

1) ajax calls new.php but the file in the PR is jsonserver.php
2) I like to name objects and arrays holding multiples in the plural, so $files
3) jsonserver.php is better than new.php, but does it really server json files or just return their names. get... might be better.
4) most people will complain about  async: false. you have a .done which is async, so there should be no need.
5) dataType: 'text' will probably work, but is it text or json?
6 I find the var filenames a little generic as a name.

**Comment by siriuswapnil** [comment]
1. That was a terrible error. Changed that. Was actually working on a different folder, forgot to change. Sorry for that.
2. Changed to $files
3. It just returns the file names. The GeoJSON Layer has everything it needs to access the files.
4. Removed that.
5. It is a filename, so it occurred to me that it was text.
6. Changed variable name.

Sorry for the careless commit.

**Comment by tim-moody** [comment]
I would take the npm run build build out of up.sh and create a separate build.sh for it.
When I do a pull and up.sh I may not want to have to rebuild main.js.

**Comment by tim-moody** [comment]
can probably remote shapes now as they just overlay stuff.

**Comment by siriuswapnil** [comment]
> can probably remote shapes now as they just overlay stuff.

Okay

**Comment by siriuswapnil** [comment]
> I would take the npm run build build out of up.sh and create a separate build.sh for it.
> When I do a pull and up.sh I may not want to have to rebuild main.js.

So a build.sh just for one statement? Probably, we could do without it

**Comment by tim-moody** [comment]
equally good
seems to work. now for the styling

**Pull request merged**
