### PR TITLE
IIAB Maps installer page explanations overhauled

### PR DESCRIPTION
**Pull request by holta**
Thanks to @avni & @georgejhunt who made this happen on 2020-09-09.

This is tested, but please review and/or submit improvements as necessary!

As is, this PR presents http://box/osm-vector-maps/installer/ as follows:

image

Refs: iiab/iiab#1605, iiab/iiab-admin-console#340

### CODE REVIEW

**Comment by tim-moody** [comment]
I prefer 

Select Map Pack to Install 
Install Selected Map Pack
Click on the Map where you want Hi-Res Satellite Images.

The numbers are clutter.

**Comment by holta** [comment]
1. Please nobody take offense but FWIW our primary conclusion during the 2020-09-09 UX review call with @georgejhunt and @avni was that newcomers (having absolutely no idea what's happening, never having talked to any IIAB folk, having no context at all) was to get completely overwhelmed by the visual workflow of the http://box/osm-vector-maps/installer/ page:

   - Why is the map serving 2 completely different interactive purposes?
   - How do I know left column actions are mandatory prerequisites?
   - ETC

   And so there was a need for numbers for newcomers to make sense of it all &mdash; barring a complete overhaul of the UX  workflows &mdash; which we agreed was not at all pragmatic for IIAB 7.2 :/

2. Whatever words are chosen, headings really do need to be as short + sweet we can make them (2 words better than 3, ideally anyway ;) for several reasons, but especially:
   - Lack of screen real estate avoids visual crowding/wrapping (there were very real problems here during my hours of testing...which is not obvious from the screenshot above, as I artificially shrank all browser fonts, i.e. I hit "Ctrl Minus-Sign" a few times, to squeeze this onto 1 page to paste into this GitHub tkt).
   - Snappy/short headlines are far more powerful in GUI/UX design...even if we do later uncover screen real estate!?

3. I changed "center of your Hi-Res" to "where you want Hi-Res" on @tim-moody's suggestion in the 3rd heading, and am very open to other changes where they powerfully help newbies!

**Comment by georgejhunt** [comment]
Looks Great! Thank you

**Comment by holta** [comment]
Hopefully @avni also can review this in the coming 24h.

As it is her work that made this happen.

**Comment by holta** [comment]
@georgejhunt how resilient are these 2 CLI commands? [*]

- e.g. if implementer loses her Internet connection, or ssh connection to IIAB, etc — do you think these commands be restarted w/o too many problems — to carry on from where they began?

- e.g. what network failure situation(s) would be most important to test in your opinion?

[*] to install a Map Pack or Satellite Photo region

**Comment by holta** [comment]
@avni @georgejhunt let's press ahead so IIAB 7.2 RC2 can be released.

This "Install IIAB Maps" page can be revised further if need be after merging, e.g. if the math/facts needs to be corrected[*] within the bottom-right where it says:

> You'll know it's downloaded and installed when http://box/maps shows Satellite Photos up to 14 levels of zoom (5 x 5 m pixels) &mdash; instead of just 10 levels of zoom (5 x 5 km pixels) &mdash; within the (square) local region you chose above.

[*] See question 2. at https://github.com/holta/iiab/blob/osm-readme/roles/osm-vector-maps/README.md as part of iiab/iiab#2551 (there is says 16X, which doesn't jive with 1000X here, so let's try to get to the bottom of this!)

**Pull request merged**
